dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

dotenv: .env

networks:
  development:
    verify: false
  goerli:
    verify: true

wallets:
  from_key: ${PRIVATE_KEY}
